#!/bin/bash

# Slurm job options (name, compute nodes, job time)
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --job-name=ascot5job
#SBATCH --time=10:00:00
#SBATCH --output=%x-%j.out
#SBATCH --cpus-per-task=1
#SBATCH --partition=standard
#SBATCH --tasks-per-node=1
# Replace [budget code] below with your budget code
# This is commented out so it will use the default project budget
#SBATCH --account=m25oc-s2778076
#SBATCH --qos=taskfarm
export OMP_NUM_THREADS=128

#in=$1

# Use "srun" to launch the job
srun --unbuffered --distribution=block:block --hint=nomultithread ./build/ascot5_main --in=./doc/tutorials/ascot_10kmarkers.h5 

#srun --time=00:10:00 --partition=standard --qos=short --unbuffered --distribution=block:block --hint=nomultithread --nodes=1 --ntasks=4 --account=m25oc-2778076 ./build/ascot5_main --in==../doc/tutorials/ascot_10kmarkers.h5
